name: Build and publish release packages
permissions:
  contents: write
on:
  release:
    types: [created, published]  # 同时支持创建和发布时触发
  workflow_dispatch:  # 添加手动触发支持
    inputs:
      tag:
        description: 'Tag to build release for'
        required: true
        type: string

jobs:
  build-linux-binaries:
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-gnu
            os: ubuntu-latest

          - target: x86_64-unknown-linux-musl
            os: ubuntu-latest

          - target: aarch64-unknown-linux-musl
            os: ubuntu-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-multilib clang cmake protobuf-compiler
          rustup default stable
          rustup update
          rustup show
          cargo -Vv
      - uses: actions/checkout@v4
      - name: Install Protoc
        uses: arduino/setup-protoc@v3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Install cross-compilation tools
        with:
          target: ${{ matrix.target }}
        if: startsWith(matrix.os, 'ubuntu') && contains(matrix.target, '-musl')
        uses: taiki-e/setup-cross-toolchain-action@v1
      - name: Build and publish
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: qdrant
          target: ${{ matrix.target }}
          token: ${{ secrets.GITHUB_TOKEN }}
          features: multiling-chinese,multiling-japanese,multiling-korean

  build-mac-binaries:
    strategy:
      matrix:
        include:
          - target: x86_64-apple-darwin
            os: macos-latest
          - target: aarch64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        run: |
          brew update-reset
          brew install gcc cmake protobuf-c
          rustup default stable
          rustup update
          rustup show
          cargo -Vv
      - uses: actions/checkout@v4
      - name: Build and publish
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: qdrant
          target: ${{ matrix.target }}
          features: multiling-chinese,multiling-japanese,multiling-korean
          token: ${{ secrets.GITHUB_TOKEN }}